### ISSUE TITLE
Import Replacement bug?

### ISSUE THREAD

**Issue by Squidyman56** [MightyPork/rpw#111]
**What happened?**
I had recently watched a tutorial on how to turn model files such as .json and being able to replace files for a recource pack for your recource pack workbench. But when I clicked the "Import replacement", it only allowed me to search for .png files. I do realize that the tutorial is quite outdated, but I figured that it would still work. This is the tutorial link: https://www.youtube.com/watch?v=zyrmqHTCXYg

**Steps to reproduce:**
Make a model via Mr. Crayfish's model creator
Download most recent linux versoin of RPW
Open RPW
Go to where the squid texture is located
Rightclick and then click Import Replacement
Look at file type. It only says .png file

**Crash report (if any)**
None I believe

**Comment by Squidyman56** [comment]
RPW versoin is 4.3.1 jar

**Comment by MightyPork** [comment]
I think you need to find the model json you want to replace in RPW and use "import replacement" on that. RPW doesn't have any concept of textures belonging to models, they're separate files.

Those files may be hidden by default bc RPW was originally meant as a "texture pack" editor, and all this stuff was added later (both to the game and to RPW).

There should be a toggle for that somewhere in the menu.

**Comment by Squidyman56** [comment]
So if I wanted to replace a mob with a different model, I couldn't?

**Comment by MightyPork** [comment]
Maybe @MCrafterzz can help you with that, I have no idea how that works. (last time I used RPW, this was all hard-coded in Java).

If the original json is somewhere in RPW, you can replace it. You should also be able to add custom files to the pack via file manager, there's a page on that in the Help dialog.

**Comment by Squidyman56** [comment]
Thank you.

**Comment by MCrafterzz** [comment]
Unfortunely mob models are still hardcoaded. Onlt block and item models can be replaced. Mob models can be replaced in pe so it probebly will come eventually but if you want it now you can use [https://optifine.net/home](Oftifine). Hope this helps!
