### ISSUE TITLE
Trying to set this up on my desktop again

### ISSUE THREAD

**Issue by MCrafterzz** [MightyPork/rpw#112]
What I did:
1. Click on the open on desktop button here on the site so that the github project excists on my computer
2. Opened the project in IntelliJ
3. Got this error:
Error Loading Project: Cannot load module rpw 

How can I fix this?

**Comment by MightyPork** [comment]
it's all messed up, i'm fixing it (also master doesn't build because of your commits to the wrong branch last year LOL)

**Comment by MightyPork** [comment]
it should be all good now.

I force pushed master to remove the mess, and merged that into development.

what needs to be done first is to move the "update file" URL somewhere else, I think ideally here into the repo (master) and access it via the blob/... github URL from RPW

**Comment by MCrafterzz** [comment]
Yay! It workes
