### ISSUE TITLE
lang and sound broken

### ISSUE THREAD

**Issue by ufoatom** [MightyPork/rpw#23]
hello, today was making a minecraft resource pack on the WorkBench when I realized that the amended language did not appear in the game ... I thought it was something in my game and redid everything manually ... and then discovered that the workbench is creating undue folder

example

the "lang" folder must be on

    assets\minecraft

The WorkBench is sending the same folder in the following directory

    assets\minecraft\minecraft

I'm playing in version 1.8, I downloaded the latest version of WB v.3.9.0, and so does ...: P

I do not know if it is indeed a bug, but I could only finish my resource pack moving the folder lang one level

![untitled](https://cloud.githubusercontent.com/assets/10383668/5603609/cc768224-9374-11e4-9a5b-38ed1eec04f2.png)

Original Text: 

ola, hoje estava fazendo um resource pack do minecraft no WorkBench quando percebi que a linguagem alterada não aparecia no jogo... achei que era algo no meu jogo e refiz tudo manualmente... e então descobri que o workbench está criando uma pasta indevida

Exemplo

a pasta "lang" deve ficar em

    assets\minecraft

o WorkBench está mandando a mesma pasta no seguinte diretório

    assets\minecraft\minecraft

Estou jogando na versão 1.8, baixei a ultima versão do WB v.3.9.0, e o mesmo acontece... :P

não sei se é de fato um bug, mas só consegui finalizar minha resource pack movendo a pasta lang um nível acima

**Comment by MightyPork** [comment]
Great report!

I didn't test sounds and lang since Minecraft 1.6.4, and something in the Minecraft assets repository changed since then, that I wasn't aware of.

I'll try to make a fix and release 3.9.1 later this month (kinda busy with school now).

For now, after exporting from RPW, do the following changes: 

Move:

    assets/minecraft/minecraft  ->  assets/minecraft
    assets/minecraft/realms  ->  assets/realms

in the exported folder.

Also notable, the "custom sounds editor" will probably not work in this version. That will be also fixed in 3.9.1.

**Comment by ufoatom** [comment]
thx, so get out a new version will download: D
there will continue to do my trick

Thank you for your attention !!! xD

**Comment by ssandweiss** [comment]
Hey @MightyPork ! I was just wondering when this fix would be implemented? This is a fantastic little app and I would love to keep using it.

**Comment by MightyPork** [comment]
whoops I forgot to mark this as fixed, there already is a new release - head over to the [releases page](https://github.com/MightyPork/rpw/releases/tag/v3.9.1)!

**Comment by ssandweiss** [comment]
Thanks @MightyPork
