### ISSUE TITLE
mcpatcher "colormap" folder not being saved.

### ISSUE THREAD

**Issue by Thieved** [MightyPork/rpw#24]
Pretty basic. I have edited the project_files folder to contain a custom birch tree color. I manually added the mcpatcher folder and colormap folder. When the project is exported, the mcpatcher folder is exported along with the ctm and font but NOT the colormap folder. The colormap folder IS IN the project_files but is being left out.

**Comment by MightyPork** [comment]
The folder project_files is where RPW stores files you "copy to project" in the asset tree.
If you want to add custom extra files, use the included_files folder.
