### ISSUE TITLE
texture is pink and black

### ISSUE THREAD

**Issue by jackmega** [MightyPork/rpw#27]
in resource pack workbench the texture appears as I want it but in minecraft it looks like two pink squares and two black squares please help!!!!!

**Comment by MightyPork** [comment]
Please provide more info.

- What RPW version you have
- What texture you are trying to change
- Maybe link the pack so I can try it myself... (use dropbox, google drive or something)

(And adding FIVE exclamation marks will — surprise — not help this being resolved any faster)

**Comment by jackmega** [comment]
I am using the latest version 
I'm changing glowstone and redstone

**Comment by MightyPork** [comment]
Then I have no idea, must be some mistake on your side (how are you editing it?)
![gfhdfhfd](https://cloud.githubusercontent.com/assets/2041118/6994862/3ee67eea-db28-11e4-8b9b-2a5d330c6b1f.png)
. I tried it and it works as expected.

**Comment by jackmega** [comment]
Importing an image

**Comment by MightyPork** [comment]
well make sure the image ur importing is PNG

**Comment by jackmega** [comment]
the image is png

**Comment by jackmega** [comment]
is there a max texture pack size?

**Comment by MightyPork** [comment]
I don't think so, but it's not a good idea to have one texture different size than the others (also you probably need some sort of HD patch for larger images to work, not sure.

**Comment by jackmega** [comment]
k thx
