### ISSUE TITLE
Random ideas

### ISSUE THREAD

**Issue by xbony2** [MightyPork/rpw#29]
Here's a bunch of bad ideas you might want to look into:
* A built-in editor.
* Letting assets being extracted by a different source, *cough* MultiMc and the FTB Launcher.
* An API.
* A way to hide sounds, like the lang. hider.

**Comment by PvtPirate** [comment]
- announcing current latest version on the website

**Comment by MightyPork** [comment]
the website, you mean ondrovo.com/rpw ? Yeah I can do that @PvtPirate

**Comment by MightyPork** [comment]
I've implemented hiding sounds, for supporting unofficial launchers I'd need to know how they work, which I do not, so that's not gonna happen. Someone else may send a PR.
