### ISSUE TITLE
"Import stitched PNG from..." don't working

### ISSUE THREAD

**Issue by misterFunky** [MightyPork/rpw#30]
Hey!
If I edit the exported stitched PNG's and I want import them to the program, the program throw out a error. Pls fix it.
Runtime log: http://pastebin.com/qN55AqKK
(Windows 8.1 x64, tried with Java 7u67 [64 bit] and Java8u40 [64 bit])
Sorry for my english.
mr. Funky

**Comment by MightyPork** [comment]
Sorry for.. um, late reply. I was busy procrastinating and didn't notice this.

It'd help if you could send me the folder with the stuff you were trying to import (the stitched texture, json file and the other stuff).

I have not written this extension of RPW, so I don't really know how it works, but I believe I'll be able to fix it if I can reproduce the issue locally.

**Comment by MightyPork** [comment]
I cannot reproduce this glitch.
