### ISSUE TITLE
"download latest version" opens InternetExplorer

### ISSUE THREAD

**Issue by PvtPirate** [MightyPork/rpw#34]
maybe you can change it to open the user's standard browser instead of IE, because IE crashes on me, but Mozilla works fine.

**Comment by MightyPork** [comment]
Um, it opens system default browser. It must be something in your system settings, I certainly do not intend to open IE :D

**Comment by PvtPirate** [comment]
strange... IE is system default on all MS systems, but my standardbrowser is Mozilla Firefox.
maybe you can add copy adress to clipboard function, so i can open it in mozilla or whatever browser i want to use. at the moment i just open the forum or your website manually.

**Comment by MightyPork** [comment]
I think I'll add a field to the Editors config dialog, so you can set your
preferred browser there. But it's not too important I think, you don't need
browser too often (only for crash report and update & help links).

I'll try to implement a fix for the slashes asap, could you check for me if
it works before I publish it? I'll let you know when it's ready.

**Comment by PvtPirate** [comment]
i know it's not too important, but it bothered me some times.
thanks :)
