### ISSUE TITLE
Armorstand bug?

### ISSUE THREAD

**Issue by Evan13698** [MightyPork/rpw#35]
Um I don't know if you forgot about it or something but my texture pack needs a new texture for armor stands and I can't seem to find any folder for ArmorStands that I can replace, I can find the item but not the actual Entity version that appears if you place the armor stand. Could u maybe make a new update or something with the file? Or please tell me where it is if the folder isn't in the right place? I searched everywhere it could be

**Comment by MightyPork** [comment]
It is there, it's just not properly placed in the Fancy tree. I'll try to improve it in next version but it's not really worth another release right now. 

With fancy tree:

![screenshot_2015-05-14_12-42-51](https://cloud.githubusercontent.com/assets/2041118/7630497/d75de87a-fa36-11e4-8ee8-8f99f26bcfa3.png)

Without fancy tree:

![screenshot_2015-05-14_12-43-07](https://cloud.githubusercontent.com/assets/2041118/7630499/db82f9ea-fa36-11e4-96ec-f543efaea139.png)

**Comment by MightyPork** [comment]
Fixed in 4.1.0
