### ISSUE TITLE
Allow different MC folder for extracting and exporting

### ISSUE THREAD

**Issue by MightyPork** [MightyPork/rpw#37]
I'm not sure this is an important feature, but would be a welcome addition.
Could be added when I have too much time, I guess.

**Comment by PCSource** [comment]
I would like this to happen since I use MultiMC

**Comment by Xolroc** [comment]
Definitely an important feature. I want to use this, but I use ftb which installs minecraft in C:/ftb/<modpack name>.

**Comment by hanleybrand** [comment]
I also use MultiMc, so the app closes on startup for me currently.

**Comment by MightyPork** [comment]
closing in favor of #59 whihc will hopefully be implemented in the next release.
