### ISSUE TITLE
problem with RPW and mods...

### ISSUE THREAD

**Issue by supremegamer76** [MightyPork/rpw#39]
hi I still have a problem with loading RPW with mods... it freezes for no reason even if I'm loading it for vanilla minecraft... probably because I have mods installed, but I don't want of get rid of them so idk what to do about it.

**Comment by Jiggy-12321** [comment]
It works for me. Any mod that I load allows me to add textures. It may be a one time glitch or bug, since no one seems to be able to reproduce it, including me. I can look into it.

**Comment by MightyPork** [comment]
Well what can I say... I tried it with the provided .minecraft folder, and it extracted it - including the mods - without any problems.

It "froze" for a few secs in two places, but that's only to be expected, with such large mods.

![Uploading Screenshot_2015-05-26_08-49-17.png…]()
