### ISSUE TITLE
White Square Around Item

### ISSUE THREAD

**Issue by AceFlameGaming** [MightyPork/rpw#42]
After editing an item on my Windows 8.1 computer, there is a white square around item textures in-game. Plz fix so I can make better weapon and food textures. Thanks in advance if you do, and other than this bug, as far as I can tell, your software works incredibly well. Props to you!

-AceFlameGaming

**Comment by MightyPork** [comment]
Use an image editor - eg. GIMP, not crap like MS paint.

**Comment by AceFlameGaming** [comment]
Yea. MS is crap. Thx for replying to my question anyway.

**Comment by AceFlameGaming** [comment]
Well, MS Paint anyway...

**Comment by MightyPork** [comment]
Nono you got that exactly right, MS is crap :P
That's why I'm on Linux ^^
