### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by skracked** [MightyPork/rpw#44]
First off, any empty space on an item or block is replaced with white. I've tried everything I know of to get rid of it, but it won't go away. Secondly, on the grass block, the dirt is green. Green! This I have also tried to fix, to no avail. Please help!
![2015-05-29_17 54 55](https://cloud.githubusercontent.com/assets/12789985/8027043/517e7900-0d54-11e5-94d7-5030c2f38926.png)

**Comment by Jiggy-12321** [comment]
You didn't replace the original texture.

**Comment by MightyPork** [comment]
Both issues are caused by you using MS paint instead of a graphics editor.

**Comment by skracked** [comment]
What kind of graphics editor do you suggest?

**Comment by MightyPork** [comment]
I use GIMP. I've heard some people use Paint.NET with good success, too.

**Comment by skracked** [comment]
Ok, so i've downloaded and installed both(i think i'll use paint.net)... but the editor still uses MS Paint! How do I get it to use the other program?

**Comment by skracked** [comment]
I'm now using paint.net with great results. Thanks for the help!
