### ISSUE TITLE
Paint used instead of GIMP

### ISSUE THREAD

**Issue by CrazyCanine** [MightyPork/rpw#53]
hi I tried to make GIMP my default editor but it still keeps using paint

**Comment by MightyPork** [comment]
Look in the runtime log - it'll tell you what's wrong.

I think you must've configured Gimp wrong in the *Settings>Configure Editors* dialog, so it failed to run it, and continued to launch the default editor.

**Comment by CrazyCanine** [comment]
wait i shouldnt be asking you this but does GIMP run on windows 10 insider preveiw with RPW?
it opens fine for me but ill send you a pic of why im confu
![image](https://cloud.githubusercontent.com/assets/13059933/8390373/bc1caff4-1c98-11e5-9cb6-089548b574f3.png)
sed

**Comment by MightyPork** [comment]
I have no experience with Windows (at all, latest version I used is XP). But I suspect you picked a link instead of the actual exe file. Try with the exe (it'll be in Program Files, I believe).

**Comment by CrazyCanine** [comment]
i used the exe file and it is in software but it still doesnt work

**Comment by Jiggy-12321** [comment]
I am seeing this, and people on the forums are reporting it. I think it may be a bug. I tried it too, and it doesn't use GIMP.

**Comment by MightyPork** [comment]
I'll try install Windows in a VM and debug it - may take a while, sorry.

**Comment by Jiggy-12321** [comment]
Debugging didn't help. I can't pinpoint the file causing it, but I feel it may be a compatibility issue with some lines of code and some libraries. It's always pointing me to certain files tied to certain libraries, but I don't have the time right now to parse every single file/Java library that its pointing me too. Will check when I get home...

**Comment by MightyPork** [comment]
You could've as well just said "dunno what's causing it"

**Comment by MightyPork** [comment]
Well I cannot reproduce the problem, it seems.

See here how to configure the editor: https://github.com/MightyPork/rpw/issues/58#issuecomment-127018518

**Comment by Jiggy-12321** [comment]
After much debugging, you just have to reinstall -.- I can't replicate it after installing. Upgrading Windows versions must mess with some library or something... Same thing happened to my drivers. I had to reinstall.
