### ISSUE TITLE
Models are missing in 4.1

### ISSUE THREAD

**Issue by fusionlightcat** [MightyPork/rpw#55]
The models folder is missing in 4.1.

(I dont know if it is fixed in 4.2, but if yes it would be nice if you could add it to the list of fixes) ;)

Also id like to thank you for making your tool with java (multiplatform), perfect for linux users like me.

**Comment by MightyPork** [comment]
Make sure you have models enabled (in the view menu).

**Comment by fusionlightcat** [comment]
I'm sorry, i did not notice that... Thankyou for your help anyway ;)
