### ISSUE TITLE
extraction window

### ISSUE THREAD

**Issue by Jiggy-12321** [MightyPork/rpw#56]
the extraction dialogue prompts confirmation dialogues that appear by default behind the extraction window, which at the same time freezes, making it impossible to actually click the new windows and thus finish the extraction problem. the work around is  by using the task administrator on Windows 7-8 to maximize these prompts and manage to use them in the corner of the screen where the extraction doesn't cover it. After finishing you couldn't use the close button either, so we had to end the process.

**Comment by MightyPork** [comment]
yes I know about this. Perhaps a workable workaround is to disable the information dialog for Windows.

**Comment by MightyPork** [comment]
oh by the way, after the asset extracting is finished, if you kill it with task manager, it should start normally next time. (I think)

**Comment by MightyPork** [comment]
This is now fixed in "dev" branch. Still have to work out one bug, but extraction is now almost flawless on windows.

**Comment by MightyPork** [comment]
Confirmed on Windoge 8 to work OK.
