### ISSUE TITLE
"Importing Minecraft assets" Window should be an actual Window

### ISSUE THREAD

**Issue by zommuter** [MightyPork/rpw#57]
Currently it sticks to foreground without any entry in Windows' task bar, which is really annoying when you want to do something else than watching the import progress.

**Comment by MightyPork** [comment]
yes I'm aware of it, Windows is acting weird. Fix is planned.

**Comment by MightyPork** [comment]
Closing in favor of #56, subscribe there if you want updates.

**Comment by zommuter** [comment]
will do, thanks
