### ISSUE TITLE
Widows 10 Reset...

### ISSUE THREAD

**Issue by skracked** [MightyPork/rpw#58]
When I got Windows 10, RPW went back to using MS Paint instead of paint.NET! Is there a way to fix this?

**Comment by MightyPork** [comment]
I don't have Windows 10, but I tried running Windows 8.1 in VirtualBox and this is how you should configure the editor.
Make sure your settings match the current location of the Gimp EXE:

![screenshot_2015-08-02_13-38-08](https://cloud.githubusercontent.com/assets/2041118/9025961/0a2145e4-391c-11e5-9816-481b86d9ac94.png)
![screenshot_2015-08-02_13-38-46](https://cloud.githubusercontent.com/assets/2041118/9025962/0a22377e-391c-11e5-94fd-01fc71834a19.png)

**Comment by Jiggy-12321** [comment]
Reinstall GIMP?

**Comment by skracked** [comment]
Fixed

**Comment by Jiggy-12321** [comment]
User (and I) have found a fix. Closed.

**Comment by MightyPork** [comment]
fix = reinstall gimp, then?

**Comment by Jiggy-12321** [comment]
Essentially. When you upgrade.
