### ISSUE TITLE
Bug found!

### ISSUE THREAD

**Issue by MrPorkey** [MightyPork/rpw#61]
While using the mrcrayfish modelcreator, the textures most of the times won't show up when you'd place the block model. what can i do about that?

**Comment by MightyPork** [comment]
no clue, would have to see the files

**Comment by MrPorkey** [comment]
cheked files, evrything is fine in the json file, cause it doesn't use the
null but it does use the block, but texture won't show up. what now? qq

2015-09-19 15:28 GMT+02:00 Ondřej Hruška <notifications@github.com>:

**Comment by Jiggy-12321** [comment]
MrPorkey, it's probably that your .json files from mrcrayfish modelcreator is trying to unsuccessfully overwrite the default images.

**Comment by MrPorkey** [comment]
Could it be because im using the furnace to model? maybe thats why, and im
having glass textures in it, im sure that has something to do with it.

2015-10-02 23:05 GMT+02:00 Joaquin Lainson <notifications@github.com>:

**Comment by MightyPork** [comment]
Can you post the files like I asked before, preferably the whole pack?  We're just shooting in the dark now.

**Comment by MrPorkey** [comment]
Witch files, the json file?

2015-10-04 17:09 GMT+02:00 Ondřej Hruška <notifications@github.com>:

**Comment by MightyPork** [comment]
dunno, the whole pack preferably. It's quite impossible to find the problem without being able to reproduce it
