### ISSUE TITLE
RPW Crashes

### ISSUE THREAD

**Issue by alexbp409** [MightyPork/rpw#62]
## RPW 4.3.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_60
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_60
 OS name           | Windows 10
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\John Doe\Desktop
 RPW version       | 4.3.0
 Library version   | null
 RPW path          | C:\Users\John Doe\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\John Doe\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:217)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:197)
	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:179)
	at net.mightypork.rpw.utils.files.OsUtils.initWorkdir(OsUtils.java:328)
	at net.mightypork.rpw.utils.files.OsUtils.initDirs(OsUtils.java:306)
	at net.mightypork.rpw.App.init(App.java:82)
	at net.mightypork.rpw.App.start(App.java:61)
	at net.mightypork.rpw.App.main(App.java:55)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/09/23 09:28:17
[ i ] ResourcePack Workbench v.4.3.0 (#430)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:217)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:218)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:197)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:179)
[!E!] 	at net.mightypork.rpw.utils.files.OsUtils.initWorkdir(OsUtils.java:328)
[!E!] 	at net.mightypork.rpw.utils.files.OsUtils.initDirs(OsUtils.java:306)
[!E!] 	at net.mightypork.rpw.App.init(App.java:82)
[!E!] 	at net.mightypork.rpw.App.start(App.java:61)
[!E!] 	at net.mightypork.rpw.App.main(App.java:55)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by Jiggy-12321** [comment]
I'll look into this one… can you replicate it? Does it happen all the time?

**Comment by alexbp409** [comment]
Yes it happens all the time. I am a developer myself but I could not figure out what your problem was in the source code.

**Comment by MightyPork** [comment]
I see where the NPE is coming from, but am not at all sure why it happens.

Immediate solution for you is to delete the folder `.mcRPW/tmp` manually & hope the glitch is gone.

I'll add a null check there for next release.

**Comment by alexbp409** [comment]
I can't seem to find that folder. Where exactly is it located in the root?

**Comment by MightyPork** [comment]
Root of what?

If you mean the RPW folder, if you are on Linux, it's ~/.mcRPW/tmp
On Windows it'll be somewhere in AppData, not really sure.

The location should be similar to .minecraft

**Comment by alexbp409** [comment]
Ok, thanks.
