### ISSUE TITLE
Could not find main class

### ISSUE THREAD

**Issue by AtomKekss** [MightyPork/rpw#66]
I have  a problem with the rpw on Windows.

When I try to start it, it shows that error:
 
Could not find main class: net.mightypork.rpw.App. Program will exit.

(Sorry if my English is bad, I'm from Germany

**Comment by MightyPork** [comment]
How did you try to run it?

**Comment by AtomKekss** [comment]
With Java(TM) Platform SE binary

**Comment by MightyPork** [comment]
But how. You don't get this eror if you just take the jar and run it with a JRE. Double click it or something. I have tested it on Windoze 8.1 and it worked fine.

**Comment by AtomKekss** [comment]
I just doubleclicked it but im on Windows 7

**Comment by MightyPork** [comment]
well I dunno, but the Jar works. I just tried.

Try re-downloading it maybe

**Comment by spannerman79** [comment]
Personally I'd say its a fubar java install.

Download and install the latest (Java 8) 

As your from Germany @AtomKekss this might be easier https://www.java.com/de/download/

**Comment by AtomKekss** [comment]
Yes now it's working, thank you
