### ISSUE TITLE
Read-me Suggestion

### ISSUE THREAD

**Issue by Carisus** [MightyPork/rpw#67]
I was looking for a way to create a readme that will be part of the exported resource pack. I saw the Project Summary, that would be great to include, but I would like to give credit where credit is due, and if need be include some type license. All of the things you might find in a read-me. If you already have an option for this, could you point me to where it is? Thanks

**Comment by MightyPork** [comment]
Click the folder icon on the right and it'll open the project in your file manager.

There you should see a folder called "extra_files" or something like that - anything you put in that folder will be bundled in the exported pack.

**Comment by Carisus** [comment]
Ah! And it already has a readme. Thanks for the quick response.
