### ISSUE TITLE
Export a resource pack as a folder

### ISSUE THREAD

**Issue by CopherSans** [MightyPork/rpw#69]
I love this great tool, but I want to be able to export a resource pack as a folder for testing reasons. Currently, I need to restart the MC client to test out my exported resource pack, and would be less troublesome if I only needed to refresh the textures to see the changes I've made.

Is this possible?

**Comment by MightyPork** [comment]
interesting idea, should be also easy to implement.
I'm not currently working on it, but will keep that in mind.
For now, why not set up some script that periodically unpacks your changed zip? (idk just an idea)

**Comment by CopherSans** [comment]
Thanks for the swift reply!

Yeah, I'll be making a hacky and clumsy .bat file to unpack my stuff for now. Have a nice day!

**Comment by MCrafterzz** [comment]
Added in 4.4
