### ISSUE TITLE
Cannot Use Photoshop

### ISSUE THREAD

**Issue by Raxcental** [MightyPork/rpw#72]
RPW will not load photoshop. RPW is trying to load C:\Program Files (x86)\Adobe\Adobe Photoshop CS6\Adobe Photoshop CS6\PhotoshopCS6.exe

The program runs fine. RPW just doesn't want to load it :/

**Comment by MightyPork** [comment]
You can't open textures in Photoshop with a command (that's how RPW does it), many people tried to do it and failed.

If you can't use other editor (I recommend GIMP), you can open the RPW project directory in file manager and try to open the files from there.
