### ISSUE TITLE
how do you import models in Resourcepack Workbench

### ISSUE THREAD

**Issue by alfiethomas102** [MightyPork/rpw#73]
dear mighty pork i am making a resourcepack containing a lot of my models that i cant import onto the resource pack that i made on your program is there another way to import them?
from alfiethomas102

**Comment by MightyPork** [comment]
Hi. If the models are not replacing vanilla models, RPW won't be of much help.

You can use the "folder" button on the right side of RPW to open the project folder. Whatever files you put in the `extra_files` folder will be included in the exported resource pack. Just make sure the folder structure matches that of Vanilla.

Hope that helps.

**Comment by alfiethomas102** [comment]
thanks for your help

**Comment by MightyPork** [comment]
let me know if you get it working...

**Comment by alfiethomas102** [comment]
Will do thanks!
