### ISSUE TITLE
RPW suggestion:

### ISSUE THREAD

**Issue by CommandCoder** [MightyPork/rpw#76]
I used RPW for a while now, but it it was kind of annoying me that you could not "search" for things... Maybe you could add that someday? :dancers:

**Comment by CopherSans** [comment]
You can use CTRL + F to search for stuff.

**Comment by MightyPork** [comment]
I dont think that's implemented @CopherSans

**Comment by CopherSans** [comment]
Oh, really? I've been doing it for a while now:

http://imgur.com/6TzAady

**Comment by MightyPork** [comment]
interesting, I didn't write that. Must be built into the tree table widget

**Comment by rjmaeda** [comment]
Just wondering, how do you open it again after you close it?

**Comment by MightyPork** [comment]
what do you mean rjmaeda ?

**Comment by MightyPork** [comment]
btw closing as this issue is probably solved by the already exisitng ctrl-f thing

**Comment by rjmaeda** [comment]
Oh sorry never mind
