### ISSUE TITLE
An option to "open file location" in the right click context menu.

### ISSUE THREAD

**Issue by CopherSans** [MightyPork/rpw#77]
Would be great if I could do this. Sometimes I want to open .json files using a model editor, and it can be particularly bothersome to open through the "open in file manager" option and navigate to the file again.

**Comment by MightyPork** [comment]
sounds easy to do. unfortunately I don't have time to work on rpw now, but if you know some basic java, this should be a matter of like 5 minutes

**Comment by MightyPork** [comment]
Working on this now, will be in the next patch
