### ISSUE TITLE
[CRASH REPORT]

### ISSUE THREAD

**Issue by GerMinatorCofee** [MightyPork/rpw#79]
Please follow those steps and check all the boxes `[x]` before submitting:

- [ ] I can reproduce the issue. *If you can't, then we likely can't either.*
- [x] My RPW is up to date.
- [ ] I have checked that this issue isn't reported already.
- [x] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [ ] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

*You can delete this "questionaire" if all boxes are checked - it's here 
to make sure people give some thought to their bug reports.*

---

**What happened?**

...

**Steps to reproduce:**

...

**Crash report (if any)**

...

**Comment by MightyPork** [comment]
Sorry but this is completely useless, where's the crash report?
