### ISSUE TITLE
Transparency on armor not working

### ISSUE THREAD

**Issue by MineMaster1739** [MightyPork/rpw#80]
Please follow those steps and check all the boxes `[x]` before submitting:
- [x ] I can reproduce the issue. _If you can't, then we likely can't either._
- [ x] My RPW is up to date.
- [x ] I have checked that this issue isn't reported already.
- [x ] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [x ] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

---

**What happened?**

...When texturing diamond armor layer 1 it put black in place of the transparency. When texturing other blocks with transparency this did not happen. When I loaded up Minecraft with the texture the diamond armor was black on the arms and helmet. I have tried to get it to be transparent multiple times and it does not work. I use pixelformer to edit the textures normally and the transparency was working. I have only used one version of pixelformer and pixelformer was working correctly texturing both chainmail layers. I textured another armor layer transparent after the diamond and it worked correctly.

**Steps to reproduce:**

... Use a fill tool to replace color with transparency. Then use Replace to apply the texture.

**Crash report (if any)**

...

**Comment by MineMaster1739** [comment]
![diamond_layer_1](https://cloud.githubusercontent.com/assets/18506159/14583722/5145386e-03f0-11e6-9892-5317547a3937.png)

**Comment by MightyPork** [comment]
I'll look into this, weird that it'd all of sudden stop working. May take a while til I get to it though

**Comment by MightyPork** [comment]
hmm am I wrong or does your image have no transparency in it? This smells of MS paint, tbh

**Comment by MCrafterzz** [comment]
Are you still having the problem? Can anyone else replicate this? Otherwise it probably should be closed
