### ISSUE TITLE
Language packs in RPW

### ISSUE THREAD

**Issue by DikerdodlePlays** [MightyPork/rpw#82]
After commenting on the RPW thread on Planet Minecraft, I was directed here to post an enhancement for RPW. As the title says, language packs would be a nice thing to be added, just mainly so that myself and others have the ability to rename items in-game.

I guess that's it. (I'm new to this whole 'github' thing)

**Comment by MightyPork** [comment]
I wanted to add this (possibility to add languages) but never really got
around to do it. It should be possible using the json files...

I currently don't have plans to add stuff to rpw, maybe in the summer but
that's not certain either. Feel free to send a pull request if you
perchance want to give it a go

---

If you however simply want to rename eg. carrot to pineapple and retexture
them, then you can just edit the English language file accordingly. IIRC
you can delete all but the thing you're changing from the lang file
