### ISSUE TITLE
Can't select a .app editor in MAC

### ISSUE THREAD

**Issue by dawsondiaz** [MightyPork/rpw#84]
I have a mac and I am unable to select my default editor to be photoshop. The application I would launch is a .app and instead of just selecting it, it opens it as a folder.

[Menu Option](http://cdn.dawsondiaz.com/screenshots/2016-06-09-uev17.jpg)

**Comment by MightyPork** [comment]
I don't have Mac, nor have ever used it, but from my understanding you want to use the `open` command.

Here is some reference - http://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/

As for photoshop, I'm not sure you can tell photoshop to open a file via a command. Give it a try, but it may not work. I've heard people saying it doesn't, but got no 1st-hand experience.

**Comment by dawsondiaz** [comment]
Through terminal I am able to open phtoshop with the following command:
`open -a photoshop`
I can open an image by just adding the extension `open -a photoshop image.jpg`

Is there a way I can implement this into the program?

**Comment by MightyPork** [comment]
Of course, just enter it there. It doesn't need to be a path to the executable. Can't speak for sure about Mac, but generally if it works in terminal, it'll work in rpw too

**Comment by dawsondiaz** [comment]
Great, it worked.

This is what I did in case the issue comes up in the future:
`Exec. file: "open"` and `Args: "-a photoshop %s"`

[config image](http://cdn.dawsondiaz.com/screenshots/2016-06-10-ih9we.jpg)

**Comment by MightyPork** [comment]
Thanks for the info, might come handy
