### ISSUE TITLE
Resource Pack Will Not Update In Game [Bug]

### ISSUE THREAD

**Issue by jacksonriggs** [MightyPork/rpw#85]
I haven't had an issue with this until I updated to 1.10, but the resource pack simply refuses to update the textures in game. Sometimes it will even remove all texture packs that were previously added after it exits out of the RP selection screen. I've edited multiple textures but none of them appear in-game. I'm not sure if this is a 1.10 specific issue or not, but to recreate it I would play in MC 1.10 and try to use a resource pack created with RPW. It will not update any textures and it will sometimes remove all resource packs except for the default textures. Any information on this would be great :)
EDIT: Okay it only seems to not update redstone dust, I re-textured a chest and it worked fine.

**Comment by MightyPork** [comment]
I'll look at this when I have time (likely end of this month). Haven't played 1.10 myself yet, much less with a resource pack.
