### ISSUE TITLE
Edit in Adobe Photoshop CC 2015 on OS X

### ISSUE THREAD

**Issue by nixundnomalnix** [MightyPork/rpw#86]
RPW doesn't open Photoshop when I want to Edit an image.
I'm using a Mac with OS X and Adobe Photoshop CC 2015 and I can open it in the terminal by typing "open -a "Adobe Photoshop CC 2015"  but when I'm using this comand like you described in an earlier report, nothing happens.
This is how the "Configure Editors" looks like:
Exec. file: open
Args: -a "Adobe Photoshop CC 2015" %s

It also doesn't work when I put to the args "-a photoshop %s" instead.

**Comment by spannerman79** [comment]
Dupe #84

**Comment by MightyPork** [comment]
All I can offer is this solution: https://github.com/MightyPork/rpw/issues/84#issuecomment-225305989

**Comment by mikebel3** [comment]
Solution #84 doesn't solve the problem in my opinion.  What I did to get around it was rename the folder  and app name to remove the spaces.  In my case, what I ended up with was:

Exec. file: open
Args: -a Applications/AdobePhotoshopCS6/AdobePhotoshopCS6.app %s

You may need to open the app once you remove the spaces.  The system will prompt you if you would like to update the path are keep the original.  Select update and let photoshop open and that should do it.

**Comment by MightyPork** [comment]
I'll close since the issue is not really about photoshop, but about wrong argument splitting. Gonna open another isse for it
