### ISSUE TITLE
Editor commands don't work right with spaces

### ISSUE THREAD

**Issue by MightyPork** [MightyPork/rpw#87]
Issue is with people entering photoshop path that has spaces in it as command arguments.
See #86 

We need to split by " " but treat escape sequences nicely.
Alternatively treat quoted chunks as strings.

The bug is here: 

https://github.com/MightyPork/rpw/blob/master/src/net/mightypork/rpw/utils/files/DesktopApi.java#L224

**Comment by MCrafterzz** [comment]
How can this be fixed?

**Comment by MightyPork** [comment]
The bug is essentially that it shouldn't blindly split by spaces, but take into account quotes and backslashes preceding spaces. 

I think something like this:

```
foo "bar baz" lorem\ ipsum -> foo, bar baz, lorem ipsum
```

**Comment by MCrafterzz** [comment]
Hm, that's complicated but I'll se what I can do

**Comment by MCrafterzz** [comment]
Fixed: https://github.com/MightyPork/rpw/commit/6aab5a09660d5c5b573d4b8011ce11cc77ea8797
