### ISSUE TITLE
report bug: model creator - pre4

### ISSUE THREAD

**Issue by Strigostar** [MightyPork/rpw#91]
Please follow those steps and check all the boxes `[x]` before submitting:
- [x] I can reproduce the issue. _If you can't, then we likely can't either._
- [x] My RPW is up to date.
- [x] I have checked that this issue isn't reported already.
- [x] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [x] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

_You can delete this "questionaire" if all boxes are checked - it's here 
to make sure people give some thought to their bug reports._

---

**What happened?**
the pumpkin I create (with you'r model creator) put the "no texture" texture (Black and purple checker) in minecraft.

The picture of the probleme:

![2016-08-23_21 14 08](https://cloud.githubusercontent.com/assets/21208781/17914381/ff1213bc-6977-11e6-9ba4-73fdc1c90cda.png)

...

**Steps to reproduce:**

...

**Crash report (if any)**
no
...

**Comment by MightyPork** [comment]
we don't have a model creator...?

**Comment by Strigostar** [comment]
ho! excuse me. It's your resource pack creator (but I create a new model with a model creator).
the resource pack workbench v.4.3.1

**Comment by MCrafterzz** [comment]
Are you sure that there isn't a problem with the model creator? I have used mcrayfishs and sometimes it exports a different model than the one you see. Try inporting the model into your modelling program and see if it looks ok. It could also be that it uses a texture that doesn't excist in vanilla/your textue pack

**Comment by MightyPork** [comment]
i guess we can close it, it's been a year
