### ISSUE TITLE
CRASHING!!!

### ISSUE THREAD

**Issue by RGamesGitHub** [MightyPork/rpw#92]
Please follow those steps and check all the boxes `[x]` before submitting:

- [?] I can reproduce the issue. *If you can't, then we likely can't either.*
- [x] My RPW is up to date.
- [x] I have checked that this issue isn't reported already.
- [x] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [x] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

*You can delete this "questionaire" if all boxes are checked - it's here 
to make sure people give some thought to their bug reports.*

---

**What happened?**

The program instantly crashed when I opened it.

**Steps to reproduce:**

I think having 1.10.2

**Crash report (if any)**

## RPW 4.3.1 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.6.0_24
 Java vendor       | Sun Microsystems Inc.
 Java path         | C:\Program Files\Java\jre6
 OS name           | Windows 7
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\Maggie\Desktop
 RPW version       | 4.3.1
 Library version   | UNKNOWN
 RPW path          | C:\Users\Maggie\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Maggie\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.mightypork.rpw.App.init(App.java:108)
	at net.mightypork.rpw.App.start(App.java:61)
	at net.mightypork.rpw.App.main(App.java:55)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2016/09/02 13:07:30
[ i ] ResourcePack Workbench v.4.3.1 (#431)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.3.1 (#431)
[ i ] Using library version: UNKNOWN
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
[!E!] 	at java.lang.ClassLoader.defineClass1(Native Method)
[!E!] 	at java.lang.ClassLoader.defineClassCond(Unknown Source)
[!E!] 	at java.lang.ClassLoader.defineClass(Unknown Source)
[!E!] 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[!E!] 	at java.net.URLClassLoader.defineClass(Unknown Source)
[!E!] 	at java.net.URLClassLoader.access$000(Unknown Source)
[!E!] 	at java.net.URLClassLoader$1.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.net.URLClassLoader.findClass(Unknown Source)
[!E!] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[!E!] 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[!E!] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[!E!] 	at net.mightypork.rpw.App.init(App.java:108)
[!E!] 	at net.mightypork.rpw.App.start(App.java:61)
[!E!] 	at net.mightypork.rpw.App.main(App.java:55)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
Your Java is two major versions out if date. Update asap or you'll see far more than rpw breaking.
