### ISSUE TITLE
usr/bin/gimp failing to launch

### ISSUE THREAD

**Issue by SugarGabby** [MightyPork/rpw#95]
I am using OSX el capitan and when i hit the edit button and the file is already copied to my project, it says 'Your configured image editor "usr/bin/gimp" could not be launched. Please review your settings in [Options > Configure Editors].' then it opens the file to preview.

**Comment by MightyPork** [comment]
yes, so did you configure your editor? Looks like you didn't tbh

**Comment by SugarGabby** [comment]
i dont know what to enter for gimp or how to get that info

**Comment by MightyPork** [comment]
well I know nothing about mac, but try something from here with the `open` command.

http://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/

maybe (my guess)

![screenshot_20161030_214435](https://cloud.githubusercontent.com/assets/2041118/19839858/189b40cc-9eea-11e6-9562-affa68787133.png)

**Comment by SugarGabby** [comment]
what information does the app put in to the program? (for example the filename)

**Comment by MightyPork** [comment]
The %s will be replaced with the filename

**Comment by SugarGabby** [comment]
thanks!
